name: Optimus APK Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        run: echo "date=$(date +'%Y-%m-%d-%H;%M;%S')" >> $GITHUB_ENV

      - name: Build with Buildozer
        uses: JuniorGarcias/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
          command: buildozer android debug
